name: dsgo
description: Control your Synology Download Station on the go!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.14-SNAPSHOT

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0 <2.11.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.0
  localstorage: ^4.0.0
  flutter_secure_storage: ^5.0.2
  tuple: ^2.0.0
  intl: ^0.17.0
  uuid: ^3.0.0
  file_picker: ^4.0.0
  animations: ^2.0.0
  package_info_plus : ^1.0.0
  synoapi:
    git:
      url: https://github.com/tingtingths/synoapi.git
      ref: 0.1.2
  collection: ^1.15.0-nullsafety.4
  logging: ^1.0.0
  flutter_riverpod: ^1.0.0
  url_launcher: ^6.0.0
  chunked_stream: ^1.4.0
  neat_periodic_task: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
